version: "3"
services:
  database:
    environment:
      - POSTGRES_PASSWORD=Postgres123
    image: postgres
    networks:
      lan:
        ipv4_address: 172.40.40.10

  site:
    depends_on:
      - database
    environment:
      - DATABASE_CONNECTION_STRING=Host=172.40.40.10;Port=5432;Pooling=true;User Id=postgres;Password=Postgres123
      - ASPNETCORE_ENVIRONMENT=Development 
      - COOKIE_EXPIRES_IN_MINUTES=30
      - CSP_HTTP_HEADER=img-src 'http://localhost:5000/'; report-uri /cspreport
    image: sgtux/netcorewebgoat
    networks:
      lan:
        ipv4_address: 172.40.40.20

networks:
  lan:
    ipam:
      config:
        - subnet: 172.40.40.0/24