CREATE TABLE "User" (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    LastName VARCHAR(200) NOT NULL,
    Email VARCHAR(200) NOT NULL,
    Password VARCHAR(200) NOT NULL,
    Photo VARCHAR(500),
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP
);

CREATE TABLE "Post" (
    Id SERIAL PRIMARY KEY,
    Text VARCHAR(200) NOT NULL,
    Photo VARCHAR(500) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP,
    UserId INT,
    CONSTRAINT FK_POST_USER FOREIGN KEY (UserId) REFERENCES "User"(Id)
);